query getMovieByGenre {
    movies (
      value: {genre:"Sci-Fi"},
       orderBy: [year_DESC]) {
      values {
        id,
        genre,
      	year,
        title,
        duration,
        synopsis,
        thumbnail,
        imagePath
      }
    }
}