query getMovieAction {
    movies (
      value: {id:"e3fe8d54-5057-4340-8b56-2216761c51e1"},
       orderBy: [year_DESC]) {
      values {
        id,
        genre,
      	year,
        title,
        duration,
        synopsis,
        thumbnail,
        imagePath
      }
    }
}